import type { Dependency } from "@/domain/types";
import { ORG_ID } from "./teams";

export const dependencies: Dependency[] = [
  {
    id: "dep-infra-blocks-api",
    orgId: ORG_ID,
    blockerTaskId: "task-infra-review",
    blockerPersonId: null,
    blockedTaskId: "task-api-migration",
    blockedPersonId: null,
    status: "unresolved",
    flaggedAt: "2026-08-04T14:00:00.000Z",
    resolvedAt: null,
    description: "API migration requires infrastructure security sign-off",
  },
  {
    id: "dep-api-blocks-mobile",
    orgId: ORG_ID,
    blockerTaskId: "task-api-migration",
    blockerPersonId: null,
    blockedTaskId: "task-mobile-release",
    blockedPersonId: null,
    status: "unresolved",
    flaggedAt: "2026-08-05T11:00:00.000Z",
    resolvedAt: null,
    description: "Mobile release requires migrated API endpoints",
  },
  {
    id: "dep-api-blocks-revops",
    orgId: ORG_ID,
    blockerTaskId: "task-api-migration",
    blockerPersonId: null,
    blockedTaskId: "task-revops-integration",
    blockedPersonId: null,
    status: "unresolved",
    flaggedAt: "2026-08-04T09:00:00.000Z",
    resolvedAt: null,
    description: "Revenue dashboard pipeline depends on new API",
  },
  {
    id: "dep-priya-blocks-marcus",
    orgId: ORG_ID,
    blockerTaskId: "task-pr-review-auth",
    blockerPersonId: null,
    blockedTaskId: "task-marcus-auth",
    blockedPersonId: null,
    status: "unresolved",
    flaggedAt: "2026-08-07T15:00:00.000Z",
    resolvedAt: null,
    description: "Marcus waiting on Priya's PR review",
  },
  {
    id: "dep-mobile-blocks-qa",
    orgId: ORG_ID,
    blockerTaskId: "task-mobile-release",
    blockerPersonId: null,
    blockedTaskId: "task-mobile-qa",
    blockedPersonId: null,
    status: "unresolved",
    flaggedAt: "2026-08-03T10:00:00.000Z",
    resolvedAt: null,
    description: "QA sign-off blocked on release candidate",
  },
  {
    id: "dep-rate-limit-blocks-alex",
    orgId: ORG_ID,
    blockerTaskId: "task-rate-limit-fix",
    blockerPersonId: null,
    blockedTaskId: null,
    blockedPersonId: "person-alex",
    status: "unresolved",
    flaggedAt: "2026-08-06T14:00:00.000Z",
    resolvedAt: null,
    description: "CS escalation root-caused to checkout API rate limits",
  },
  {
    id: "dep-design-resolved",
    orgId: ORG_ID,
    blockerTaskId: "task-design-system",
    blockerPersonId: null,
    blockedTaskId: "task-mobile-qa",
    blockedPersonId: null,
    status: "resolved",
    flaggedAt: "2026-07-28T10:00:00.000Z",
    resolvedAt: "2026-08-08T06:30:00.000Z",
    description: "Design tokens completed — QA can proceed with visual review",
  },
];
