import type { OrgEvent } from "@/domain/types";
import { ORG_ID } from "./teams";

export const events: OrgEvent[] = [
  {
    id: "evt-goal-retention-risk",
    orgId: ORG_ID,
    entityType: "goal",
    entityId: "goal-q3-retention",
    eventType: "goal_health_changed",
    timestamp: "2026-08-07T16:00:00.000Z",
    summary: "Q3 Customer Retention goal moved to at-risk",
    payload: { from: "on_track", to: "at_risk" },
    relevantPersonIds: ["person-priya", "person-devon", "person-sam", "person-jordan"],
  },
  {
    id: "evt-design-complete",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-design-system",
    eventType: "task_completed",
    timestamp: "2026-08-08T06:30:00.000Z",
    summary: "Elena completed mobile design system tokens",
    payload: { taskTitle: "Finalize mobile design system tokens" },
    relevantPersonIds: ["person-elena", "person-jordan", "person-priya"],
  },
  {
    id: "evt-dep-unblocked",
    orgId: ORG_ID,
    entityType: "dependency",
    entityId: "dep-design-resolved",
    eventType: "dependency_unblocked",
    timestamp: "2026-08-08T06:30:00.000Z",
    summary: "Design dependency resolved — mobile QA can proceed with visual review",
    payload: { blockedTaskId: "task-mobile-qa" },
    relevantPersonIds: ["person-elena", "person-jordan"],
  },
  {
    id: "evt-blocker-api",
    orgId: ORG_ID,
    entityType: "dependency",
    entityId: "dep-api-blocks-mobile",
    eventType: "blocker_created",
    timestamp: "2026-08-05T11:00:00.000Z",
    summary: "Cross-team blocker: API migration blocking mobile release",
    payload: { blockerTaskId: "task-api-migration", blockedTaskId: "task-mobile-release" },
    relevantPersonIds: ["person-priya", "person-jordan", "person-devon", "person-sam"],
  },
  {
    id: "evt-pr-review",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-pr-review-auth",
    eventType: "task_assigned",
    timestamp: "2026-08-07T14:00:00.000Z",
    summary: "New PR review request flagged as high-impact — blocks Marcus",
    payload: { requesterId: "person-marcus" },
    relevantPersonIds: ["person-priya", "person-marcus"],
  },
  {
    id: "evt-sla-escalation",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-sla-ticket",
    eventType: "blocker_created",
    timestamp: "2026-08-07T09:00:00.000Z",
    summary: "Enterprise customer escalation approaching SLA breach",
    payload: { hoursWaiting: 36 },
    relevantPersonIds: ["person-alex", "person-taylor", "person-priya"],
  },
  {
    id: "evt-rate-limit-progress",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-rate-limit-fix",
    eventType: "task_assigned",
    timestamp: "2026-08-06T10:00:00.000Z",
    summary: "Rate limit fix assigned to Priya — linked to CS escalation",
    payload: {},
    relevantPersonIds: ["person-priya", "person-alex"],
  },
  {
    id: "evt-marcus-progress",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-marcus-auth",
    eventType: "task_assigned",
    timestamp: "2026-08-01T10:00:00.000Z",
    summary: "Marcus started auth middleware refactor",
    payload: {},
    relevantPersonIds: ["person-marcus", "person-devon"],
  },
  {
    id: "evt-historical-complete-1",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-hist-1",
    eventType: "task_completed",
    timestamp: "2026-08-04T16:00:00.000Z",
    summary: "Platform team completed staging environment refresh (mock historical)",
    payload: { taskTitle: "Staging environment refresh" },
    relevantPersonIds: ["person-priya", "person-devon", "person-sam"],
  },
  {
    id: "evt-historical-complete-2",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-hist-2",
    eventType: "task_completed",
    timestamp: "2026-08-05T14:00:00.000Z",
    summary: "Mobile team completed push notification spike (mock historical)",
    payload: { taskTitle: "Push notification spike" },
    relevantPersonIds: ["person-jordan", "person-elena", "person-devon"],
  },
  {
    id: "evt-historical-complete-3",
    orgId: ORG_ID,
    entityType: "task",
    entityId: "task-hist-3",
    eventType: "task_completed",
    timestamp: "2026-08-06T11:00:00.000Z",
    summary: "CS team closed duplicate escalation ticket (mock historical)",
    payload: { taskTitle: "Duplicate escalation cleanup" },
    relevantPersonIds: ["person-alex", "person-taylor"],
  },
];
