import type { Person } from "@/domain/types";
import { ORG_ID } from "./teams";

export const people: Person[] = [
  {
    id: "person-priya",
    orgId: ORG_ID,
    name: "Priya Sharma",
    email: "priya@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-platform",
    managerId: "person-devon",
    title: "Senior Engineer",
  },
  {
    id: "person-marcus",
    orgId: ORG_ID,
    name: "Marcus Chen",
    email: "marcus@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-platform",
    managerId: "person-devon",
    title: "Backend Engineer",
  },
  {
    id: "person-elena",
    orgId: ORG_ID,
    name: "Elena Rodriguez",
    email: "elena@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-product",
    managerId: "person-sam",
    title: "Product Designer",
  },
  {
    id: "person-jordan",
    orgId: ORG_ID,
    name: "Jordan Lee",
    email: "jordan@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-product",
    managerId: "person-sam",
    title: "Mobile Engineer",
  },
  {
    id: "person-alex",
    orgId: ORG_ID,
    name: "Alex Kim",
    email: "alex@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-cs",
    managerId: "person-taylor",
    title: "Customer Success Manager",
  },
  {
    id: "person-devon",
    orgId: ORG_ID,
    name: "Devon Walsh",
    email: "devon@acme.corp",
    role: "manager",
    tier: "manager",
    teamId: "team-platform",
    managerId: "person-vp-eng",
    title: "Engineering Manager",
  },
  {
    id: "person-sam",
    orgId: ORG_ID,
    name: "Sam Okonkwo",
    email: "sam@acme.corp",
    role: "manager",
    tier: "manager",
    teamId: "team-product",
    managerId: "person-vp-eng",
    title: "Product Lead",
  },
  {
    id: "person-taylor",
    orgId: ORG_ID,
    name: "Taylor Brooks",
    email: "taylor@acme.corp",
    role: "manager",
    tier: "manager",
    teamId: "team-cs",
    managerId: "person-vp-eng",
    title: "CS Manager",
  },
  {
    id: "person-vp-eng",
    orgId: ORG_ID,
    name: "Marisol Vega",
    email: "marisol@acme.corp",
    role: "executive",
    tier: "vp",
    teamId: "team-product",
    managerId: null,
    title: "VP Engineering",
  },
  {
    id: "person-revops",
    orgId: ORG_ID,
    name: "Riley Park",
    email: "riley@acme.corp",
    role: "ic",
    tier: "ic",
    teamId: "team-revops",
    managerId: "person-sam",
    title: "Revenue Ops Analyst",
  },
];

export const DEMO_PERSONAS = [
  { id: "person-priya", label: "Priya Sharma — IC" },
  { id: "person-devon", label: "Devon Walsh — Manager" },
  { id: "person-jordan", label: "Jordan Lee — IC (blocked)" },
  { id: "person-alex", label: "Alex Kim — IC (CS)" },
];

export const DEFAULT_PERSON_ID = "person-priya";
