import type { Task } from "@/domain/types";
import { ORG_ID } from "./teams";

const base = "2026-08-0";

export const tasks: Task[] = [
  {
    id: "task-api-migration",
    orgId: ORG_ID,
    title: "Complete API gateway migration",
    description: "Migrate legacy gateway endpoints to new platform API layer.",
    ownerId: "person-priya",
    linkedGoalId: "goal-api-migration",
    initiativeId: "init-api",
    startDate: "2026-07-28T09:00:00.000Z",
    dueDate: `${base}9T17:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-jira",
    surfacedCount: 2,
    createdAt: "2026-07-20T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-pr-review-auth",
    orgId: ORG_ID,
    title: "Review Marcus's auth middleware PR",
    description: "Security review blocking downstream mobile integration work.",
    ownerId: "person-priya",
    linkedGoalId: "goal-platform-reliability",
    initiativeId: "init-reliability",
    startDate: "2026-08-07T14:00:00.000Z",
    dueDate: `${base}8T17:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-github",
    surfacedCount: 0,
    createdAt: "2026-08-07T14:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-rate-limit-fix",
    orgId: ORG_ID,
    title: "Fix rate limiting on checkout API",
    description: "Enterprise customer reporting intermittent 429 errors.",
    ownerId: "person-priya",
    linkedGoalId: "goal-q3-retention",
    initiativeId: "init-retention",
    startDate: "2026-08-05T09:00:00.000Z",
    dueDate: `${base}8T12:00:00.000Z`,
    status: "in_progress",
    sourceSystem: "mock-jira",
    surfacedCount: 1,
    createdAt: "2026-08-05T09:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-oncall-runbook",
    orgId: ORG_ID,
    title: "Update on-call runbook for payment failures",
    description: "Documentation task with lower immediate impact.",
    ownerId: "person-priya",
    linkedGoalId: "goal-platform-reliability",
    initiativeId: "init-reliability",
    startDate: "2026-08-10T09:00:00.000Z",
    dueDate: "2026-08-20T17:00:00.000Z",
    status: "open",
    sourceSystem: "mock-asana",
    surfacedCount: 5,
    createdAt: "2026-07-01T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-marcus-auth",
    orgId: ORG_ID,
    title: "Implement auth middleware refactor",
    description: "Blocked on Priya's PR review.",
    ownerId: "person-marcus",
    linkedGoalId: "goal-platform-reliability",
    initiativeId: "init-reliability",
    startDate: "2026-08-01T10:00:00.000Z",
    dueDate: "2026-08-12T17:00:00.000Z",
    status: "in_progress",
    sourceSystem: "mock-github",
    surfacedCount: 0,
    createdAt: "2026-08-01T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-mobile-release",
    orgId: ORG_ID,
    title: "Ship mobile v2 release candidate",
    description: "Blocked on API migration completion.",
    ownerId: "person-jordan",
    linkedGoalId: "goal-mobile-launch",
    initiativeId: "init-mobile",
    startDate: "2026-07-20T09:00:00.000Z",
    dueDate: `${base}6T17:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-jira",
    surfacedCount: 3,
    createdAt: "2026-07-15T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-mobile-qa",
    orgId: ORG_ID,
    title: "Complete mobile QA sign-off",
    description: "Waiting on release candidate.",
    ownerId: "person-elena",
    linkedGoalId: "goal-mobile-launch",
    initiativeId: "init-mobile",
    startDate: "2026-08-09T09:00:00.000Z",
    dueDate: "2026-08-11T17:00:00.000Z",
    status: "open",
    sourceSystem: "mock-asana",
    surfacedCount: 0,
    createdAt: "2026-07-20T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-sla-ticket",
    orgId: ORG_ID,
    title: "Resolve Acme Corp enterprise escalation",
    description: "SLA breach risk — customer waiting 36 hours.",
    ownerId: "person-alex",
    linkedGoalId: "goal-enterprise-sla",
    initiativeId: "init-sla",
    startDate: "2026-08-06T08:00:00.000Z",
    dueDate: `${base}8T18:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-zendesk",
    surfacedCount: 0,
    createdAt: "2026-08-06T08:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-cs-playbook",
    orgId: ORG_ID,
    title: "Draft enterprise escalation playbook",
    description: "Process improvement for CS team.",
    ownerId: "person-alex",
    linkedGoalId: "goal-enterprise-sla",
    initiativeId: "init-sla",
    startDate: "2026-08-12T09:00:00.000Z",
    dueDate: "2026-08-25T17:00:00.000Z",
    status: "open",
    sourceSystem: "mock-asana",
    surfacedCount: 0,
    createdAt: "2026-08-01T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-revops-integration",
    orgId: ORG_ID,
    title: "Wire CRM data into revenue dashboard",
    description: "Blocked on API migration for data pipeline.",
    ownerId: "person-revops",
    linkedGoalId: "goal-q3-retention",
    initiativeId: "init-retention",
    startDate: "2026-08-01T09:00:00.000Z",
    dueDate: "2026-08-14T17:00:00.000Z",
    status: "open",
    sourceSystem: "mock-jira",
    surfacedCount: 1,
    createdAt: "2026-07-25T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-design-system",
    orgId: ORG_ID,
    title: "Finalize mobile design system tokens",
    description: "Completed overnight — unblocked QA planning.",
    ownerId: "person-elena",
    linkedGoalId: "goal-mobile-launch",
    initiativeId: "init-mobile",
    startDate: "2026-07-10T09:00:00.000Z",
    dueDate: "2026-08-07T17:00:00.000Z",
    status: "done",
    sourceSystem: "mock-figma",
    surfacedCount: 0,
    createdAt: "2026-07-10T10:00:00.000Z",
    completedAt: "2026-08-08T06:30:00.000Z",
  },
  {
    id: "task-infra-review",
    orgId: ORG_ID,
    title: "Infrastructure security review",
    description: "Platform security sign-off required before API gateway cutover.",
    ownerId: "person-sam",
    linkedGoalId: "goal-platform-reliability",
    initiativeId: "init-reliability",
    startDate: "2026-07-18T09:00:00.000Z",
    dueDate: `${base}6T17:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-jira",
    surfacedCount: 1,
    createdAt: "2026-07-18T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "task-devon-1on1-prep",
    orgId: ORG_ID,
    title: "Prepare platform team status for standup",
    description: "Manager coordination task.",
    ownerId: "person-devon",
    linkedGoalId: "goal-platform-reliability",
    initiativeId: "init-reliability",
    startDate: "2026-08-07T16:00:00.000Z",
    dueDate: `${base}8T10:00:00.000Z`,
    status: "open",
    sourceSystem: "mock-asana",
    surfacedCount: 0,
    createdAt: "2026-08-07T16:00:00.000Z",
    completedAt: null,
  },
];
